server:
  port: 9020

spring:
  application:
    name: kafka_producer

  r2dbc:
    url: r2dbc:pool:postgresql://${DB_HOST:localhost:5436}/${DB_DATABASE:kafka_producer_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost:5436}/${DB_DATABASE:kafka_producer_db}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  kafka:
    template:
      default-topic: telemetries-topic
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

redis-cache:
  enabled: ${CACHEABLE:true}
  host: ${REDIS_HOST:localhost:6379}

app:
  batch:
    size: 1000
  agent:
    load: true
    count: 1000
  message:
    ratePerMinute: 5

logging:
  level:
    org:
      springframework:
        data:
          datasource: DEBUG
