server:
  port: 9020

spring:
  application:
    name: kafka_producer

  r2dbc:
    url: r2dbc:pool:postgresql://${DB_HOST:localhost:5436}/${DB_DATABASE:kafka_producer_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost:5436}/${DB_DATABASE:kafka_producer_db}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  kafka:
    template:
      default-topic: default-topic
    producer:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  agent:
    load: true
    count: 10
  message:
    ratePerMinute: 10

logging:
  level:
    org:
      springframework:
        data:
          datasource: DEBUG
